const fakeDonations = [
  {
    id: 1,
    transferredAmount: 1734,
    campaignTitle: "termes amplus",
    donorName: "Ada Hagenes",
    status: "Pending",
    date: "20/10/2022",
  },
  {
    id: 2,
    transferredAmount: 4320,
    campaignTitle: "vita ut",
    donorName: "Donor1",
    status: "Pending",
    date: "20/10/2022",
  },
  {
    id: 3,
    transferredAmount: 2904,
    campaignTitle: "creber curvo",
    donorName: "Victoria DuBuque",
    status: "Pending",
    date: "20/10/2022",
  },
  {
    id: 4,
    transferredAmount: 5708,
    campaignTitle: "terror abscido",
    donorName: "Donor1",
    status: "Pending",
    date: "20/10/2022",
  },
  {
    id: 5,
    transferredAmount: 1055,
    campaignTitle: "vinculum versus",
    donorName: "Edmund Stanton III",
    status: "Pending",
    date: "20/10/2022",
  },
  {
    id: 6,
    transferredAmount: 1055,
    campaignTitle: "vinculum versus",
    donorName: "Edmund Stanton III",
    status: "Pending",
    date: "20/10/2022",
  },
  {
    id: 7,
    transferredAmount: 1055,
    campaignTitle: "vinculum versus",
    donorName: "Edmund Stanton III",
    status: "Pending",
    date: "20/10/2022",
  },
  {
    id: 8,
    transferredAmount: 1055,
    campaignTitle: "vinculum versus",
    donorName: "Edmund Stanton III",
    status: "Pending",
    date: "20/10/2022",
  },
  {
    id: 9,
    transferredAmount: 1055,
    campaignTitle: "vinculum versus",
    donorName: "Edmund Stanton III",
    status: "Pending",
    date: "20/10/2022",
  },
  {
    id: 10,
    transferredAmount: 1055,
    campaignTitle: "vinculum versus",
    donorName: "Edmund Stanton III",
    status: "Pending",
    date: "20/10/2022",
  },
];
// console.log(fakeDonations);

export default fakeDonations;
