export const fakeCampaigns = [
  {
    id: 1,
    title: "torqueo temporibus",
    target: 279,
    description:
      "Verto sui spargo defaeco. Sumo abduco magni valens. Cometes sequi iusto sperno animadverto cogito doloremque defetiscor aspernatur. Infit textilis amor. Suadeo umquam demergo brevis sint acervus suscipit claustrum absum. Illum blandior adulatio tabernus defendo ipsum clarus ipsam. Distinctio terga ventus pel artificiose ipsam comptus. Valeo timidus ventito. Explicabo sunt at aestus vesco utroque crastinus vomer versus. Celo thalassinus voluntarius pauci suffragium aranea admoneo certus quidem. Deleniti spectaculum cenaculum usus neque sollicito clibanus. Coaegresco bis tempus vulgo adstringo templum concedo causa totidem. Terebro caries ademptio demulceo creber. Tondeo admiratio appello coadunatio blanditiis somniculosus. Ciminatio veniam vestrum. Auctus depereo argentum territo ultra. Pax delibero admoveo demulceo suscipit tot vinco claudeo deputo ulciscor. Corporis ocer odio creptio cultura. Nobis aureus suffragium cursus strenuus aedificium desipio. Inventore adeo arcesso ara advoco. Demitto cinis distinctio minus ustilo beneficium. Voluptatum tribuo voluptates nesciunt modi vicissitudo. Voluptatem suadeo degero vitiosus spiritus teres cultellus defendo spargo terra. Umbra approbo virgo vinculum magni ater tabella tergum. Summisse deprimo demulceo vigilo bellum recusandae audentia carpo subiungo. Beatae vilicus suasoria sordeo terra eveniet conduco tener. Barba et cruciamentum. Voluptatibus cuppedia tot caveo inventore cunabula alias. Spectaculum vivo conitor. Aequitas animadverto cupiditate abeo vulpes. Conatus amaritudo suppellex delego. Congregatio tamquam triumphus vulpes sursum acer usus arcus denuncio. Vicinus sub tabesco depraedor tepidus cubo hic debeo candidus. Cupressus speculum appono cado adhaero decumbo. Clibanus denuo est somnus utilis coerceo defluo allatus. Beneficium ager tenetur capitulus soleo infit. Decor conturbo testimonium asperiores textilis necessitatibus caries occaecati sunt. Adflicto necessitatibus peior solium iusto officiis subseco urbs dolor. Perferendis vaco amplexus vulariter aeternus compello vita crustulum.",
    amountContributed: 270,
    status: "pending",
  },
  {
    id: 2,
    title: "curvo advenio",
    target: 137,
    description:
      "Spectaculum voluptates contabesco. Utor damnatio corrupti pel summa. Strenuus aliquid id suffragium degenero thorax circumvenio tyrannus. Caveo theatrum pax. Cauda atqui sopor brevis. Caries solio adduco. Tracto combibo dolor vitium tumultus a supplanto aiunt eius vesper. Cognatus cursim vita nesciunt voco terror agnitio tres derelinquo cauda. Verumtamen defessus bibo cogo voluptatibus urbanus. Timor umerus audacia temeritas aggredior solvo alter claustrum. Compello suppellex adficio arbustum stultus vulgaris cribro tenetur maiores. Civis anser varius. Deprimo absque avaritia solus blanditiis numquam consuasor ademptio. Defendo coadunatio supellex quisquam sursum repudiandae. Doloribus nulla cedo versus deinde. Amor verbera explicabo decens usque templum centum tamen apparatus tardus. Aperiam summisse cado subnecto pecto caelestis adflicto. Atrox corroboro verto autus odio repellendus capio cattus votum cupressus. Harum totus deprimo argentum pecus statua tollo comes ocer. Bellicus coadunatio decet. Umquam conservo alienus officiis nesciunt coerceo ut. Curiositas theologus paens. Nemo suus antiquus super. Abbas talis tabernus thymbra aeternus attollo. Adsum confero adficio currus utor altus. Patria eveniet animus surgo sortitus totam umquam cogo calcar. Aspicio deprecator amo voluptate. Currus conspergo copia. Utilis astrum cena non. Vir contego tredecim. Cribro error patrocinor vinitor baiulus attero ventus vivo. Adficio provident perferendis voluptate cruentus vicinus. Triduana totus volup agnitio tantillus collum suffragium. Careo ullam celebrer caries utor volaticus quia ait error. Strenuus utrimque sodalitas taceo adsuesco ancilla cogito timor corrumpo terminatio. Arcesso mollitia cogo usus sui spiritus. Laboriosam suasoria stips valens. Condico turba sperno undique utor curriculum sapiente spiculum vito. Sollicito est speciosus creta audeo a attollo. Vigilo aeternus defero tracto cultellus aggredior claustrum cruentus vigilo bellicus.",
    amountContributed: 107,
    status: "active",
  },
  {
    id: 3,
    title: "allatus blanditiis",
    target: 507,
    description:
      "Adulatio absum aureus conitor cernuus. Amissio tabesco nisi voluntarius tepesco temeritas angelus aeternus congregatio aufero. Astrum allatus bene vitium supplanto agnosco. Cicuta coerceo correptius demulceo iusto aegrus apto. Defluo voveo canto comis architecto. Strues denique quo antea apud calculus tam fuga super auctor. Ustulo magni illo subseco. Veritatis ocer crinis. Delicate utor aro angulus pax debitis thermae sui appello. Sequi villa aqua aufero corporis absorbeo assumenda. Vulnero tantum amiculum aperiam minima alo abundans. Thermae amissio tempus praesentium sit vulariter. Angelus caste capillus teneo. Textus cervus vulgivagus vesica balbus iusto arca. Comitatus deprecator cernuus vis. Tenax censura nobis. Adeo administratio animadverto. Laboriosam caecus aptus. Facere vulnus vereor tristis aestus conscendo. Vester aetas cenaculum voco. Aro depraedor vindico patrocinor aeternus auxilium. Aliquam aranea tantum voluptas. Ratione verecundia adopto ambulo auctor. Curriculum anser aduro cogo soleo dedico sodalitas. Alius aegre tardus. Amplus voluptates denique aer sursum cicuta talio. Appello tondeo optio sperno arceo patruus vobis. Sto beneficium tempora utique sustineo decet. Copiose arcus aureus. Thema sulum bardus. Taceo bellum tenus apparatus apto strues. Confido theca denuo vetus officiis caute beatus tibi. Audax facere basium verbum cohors amaritudo. Custodia molestiae exercitationem decumbo tandem cibus.",
    amountContributed: 280,
    status: "active",
  },
  {
    id: 4,
    title: "crapula tergo",
    target: 986,
    description:
      "Averto arceo vulgo voluptas venia cimentarius socius. Unde provident cavus consuasor ocer appello pecus. Subseco curso corrupti umquam. Deprimo strenuus valens tubineus vobis talus corpus. Aestivus canis vester clementia umbra damnatio carbo. Cupiditas veritas et spoliatio supplanto. Ustilo terra thermae crepusculum caries cibo depromo. Officiis saepe copia eius repellendus aestivus vesco sui validus. Nobis agnitio comitatus vinculum corrumpo curvo clam victus demitto. Cibus celebrer vulgaris. Spoliatio aestus adiuvo auctor. Arguo coruscus tristis utroque fugit. Cribro suus demens custodia ascit solus beatae despecto. Credo ventito compello circumvenio quia adversus aveho ea demitto dolor. Tersus doloribus ulterius calamitas quidem corrigo custodia comminor strues officiis. Degusto decimus compono fugit vicissitudo comedo vestrum umerus. Aufero tenus considero creptio desipio nostrum basium corpus curia. Admitto contra comis vestigium aranea astrum caveo. Ver cupressus dens tempora adiuvo vulpes ultra tabgo suasoria tristis. Possimus aperiam vulgaris verumtamen aptus appono somniculosus facere. Adhaero cena aggredior sui amplitudo odit. Tamen sunt coerceo cupressus quam tego volutabrum. Degusto usque abeo basium supra atrocitas averto sulum possimus. Vacuus comitatus vaco supplanto demo. Ante adsuesco debeo decipio harum agnosco. Volubilis tollo super barba. Vox subvenio consuasor alius vel demulceo porro molestiae contigo labore. Sublime astrum crustulum atque. Sequi acies coniecto culpo admiratio angelus ex. Amplus pecco apto tum. Quidem enim adicio quam adfero brevis abbas.",
    amountContributed: 10,
    status: "active",
  },
  {
    id: 5,
    title: "perferendis alo",
    target: 737,
    description:
      "Cicuta arx cotidie. Cibo dolores trado absens pariatur aliqua. Voluptatibus creo video tactus baiulus circumvenio sunt. Tenax adsidue constans tactus catena absque creta comes. Terra sint catena at in cura video ustulo impedit. Socius curatio pel. Volup corporis abbas argumentum non contigo supra velum ventus. Vulgus adaugeo ventus sulum. Decor denuo varius. Collum tabernus thesaurus tripudio uter tersus. Quis sapiente ubi. Vito trans altus deinde vulgus ea decor appono labore supellex. Curvo tollo ager demo caterva deprimo valde triduana cornu agnitio. Audax aut colo abbas una absorbeo amoveo termes. Alias verbera admoneo umerus viscus auctus asper amitto. Accusamus sulum arto perferendis vereor. Desparatus aut ventus viriliter adsuesco voluptas. Strenuus cupressus canis. Triumphus eos admoneo deorsum accusator eligendi. Copia acies chirographum vos turpis vesco volva ago cornu magnam. Subvenio abstergo statua abutor carus totus dolore coepi facere. Amplitudo comitatus conforto stipes. Thesis tantillus odio. Valetudo minima vespillo sum. Nesciunt appono cuppedia ars ulciscor comburo degenero torrens spiculum debilito. Caterva triduana undique cupiditas concido cupiditate censura utique. Defero bos deserunt absorbeo theatrum stillicidium artificiose suscipio terminatio. Spargo contra consectetur vulgo adamo vulgo colligo corrumpo. Pectus sufficio chirographum corrumpo degenero nam ex cattus tego. Calco accusantium sortitus sursum sequi alveus vetus statim. Crustulum virgo expedita verbum labore patrocinor paens. Carus supra ullam supellex placeat. Demonstro praesentium delego consequatur patria trucido conitor titulus cubicularis.",
    amountContributed: 321,
    status: "active",
  },
  {
    id: 6,
    title: "vulgivagus vulnus",
    target: 682,
    description:
      "Vero crudelis verus aspernatur sopor eveniet arcus omnis tondeo tui. Capio voluptate vinco. Defaeco vapulus temperantia cunctatio curto beatae. Repellendus cinis voluptatem complectus conculco tui vel terreo. Atque cernuus modi acerbitas. Acerbitas texo expedita crudelis volutabrum balbus ver. Communis delicate alioqui magni. Suppellex tendo pariatur utrimque votum solus cupiditate decet demo solum. Votum vulgaris somniculosus vilicus stipes voluptate tego sui aiunt inflammatio. Speculum vita tempore curia ab convoco chirographum. Asperiores spoliatio voluptatibus acies decor pauci degero spectaculum antea. Cursim carpo consequatur accendo natus quas temptatio vergo cado. Summisse est admoveo conatus cultellus nihil aegrus adfero coma. Adsum aduro theologus tribuo deleo acceptus ait. Placeat turbo ex inflammatio. Asperiores terga comburo comes compono dignissimos custodia tamen. Aegrotatio confugo amoveo aduro curo enim. Circumvenio vicissitudo depromo celebrer. Aegrotatio vulticulus abeo capitulus aperio suffoco altus adfectus considero. Acer crepusculum corrupti ver. Absque conduco supra sonitus impedit spargo degero tolero acervus videlicet. Capillus terga sto vaco. Speculum summisse rerum capto denique curriculum explicabo. Torrens testimonium eum subnecto autem advenio curis paens pauper. Totus cursus demo patior quo thesis vinum. Cupiditas truculenter deleo adulatio aro officia apto cubo. Articulus traho terebro canonicus ager verto. Auditor aeternus clementia centum crustulum voluntarius subvenio adulatio tersus vulgus. Spiritus derelinquo corrigo ad. Tenetur perferendis solutio adflicto debilito vito. Volutabrum coniuratio vulnus vaco earum auxilium damnatio clam bellicus. Ab nostrum voluptas amplitudo aranea umbra conventus cibo clarus. Ager utpote tamquam vomer coerceo alienus ocer creptio nisi. Credo eum arguo officiis ventus trucido coma solium deleniti. Suscipio vix tergum addo quod natus. Incidunt amicitia vivo in cursim tunc claro compono.",
    amountContributed: 490,
    status: "pending",
  },
  {
    id: 7,
    title: "iste advenio",
    target: 580,
    description:
      "Vilis non tabella. Vestigium pauci aeneus caput. Voluntarius comis unde ademptio cernuus canis attero. Synagoga cibo tener nesciunt cerno custodia ubi recusandae beatus verecundia. Tenuis minus vociferor custodia ultio cruciamentum theca aestas dapifer via. Consequatur totidem capio civis solus volva. Enim candidus universe censura tego necessitatibus. Admitto patruus votum demitto colo thesaurus versus. Bellum inflammatio annus tener cariosus ustilo. Corporis caput substantia conqueror tribuo. Vel antea calculus certe. Accommodo apto dicta amet vero suggero vergo comminor approbo. Aestus comburo fugiat. Sapiente voro vix vicissitudo socius agnitio terror aperte veritas. Taceo bellicus dedecor certe stips textus trans arguo suspendo. Textor quos peccatus. Repellendus acer tergum demergo centum aeger. Delectatio vorax modi. Adulescens ipsum odit accusamus conspergo adfectus totidem. Spero alo cunae. Quam ea sed ait avarus verto volup ratione bestia. Eveniet cunae eius vehemens apparatus. Suppellex spero solitudo itaque despecto usque concedo. Commodi succurro provident. Sublime cinis vivo coaegresco cunabula. Vetus placeat circumvenio doloribus collum speculum ea. Adamo ciminatio enim. Voluptas deludo tibi stips. Cruentus porro suffoco cura suscipit tardus derideo. Tonsor ciminatio conscendo pecus tricesimus pectus. Tripudio baiulus depopulo. Ustulo caelum torqueo. Tertius delicate cunctatio dens vallum adulescens. Aegrotatio amplexus aperte. Veritatis vulticulus velociter sustineo atrocitas ullus. Vita aeternus sufficio cunae certus depulso. Bestia deleniti bardus tepesco deludo tametsi nemo aufero tempora. Avarus abeo surculus celo architecto curis strenuus.",
    amountContributed: 580,
    status: "pending",
  },
  {
    id: 8,
    title: "placeat ex",
    target: 758,
    description:
      "Adfero statim vitium dolorum aveho congregatio. Acer delinquo tot architecto tollo caute colligo non quaerat talis. Dolore dolor eos. Tego aestivus bellicus ara culpa viduo doloribus enim cibo. Unde adflicto architecto tredecim nam textus umbra temeritas nam tibi. Celer arbitro demergo cupiditate nobis tantillus. Dignissimos uberrime conitor atqui vindico acidus succurro optio. Unus canis ars cavus assentator. Amitto aut saepe. Cura infit vilicus. Altus deserunt sursum appello summa. Ancilla ceno tergo aspicio possimus. Aqua stillicidium aetas ubi. Aveho angelus ter auctus decerno ciminatio adhuc annus vere. Ventito contigo vestigium. Teres denuo turpis harum. Tribuo vix cunctatio antiquus. Vitium vereor desparatus. Desparatus peior summopere deprimo cena quasi pecto curriculum. Auctus excepturi sufficio. Amoveo cauda vel ut quasi. Ipsam traho voco cruciamentum suspendo. Spiculum aeneus venia paulatim vulgo auctor culpa delectus arbustum suffragium. In eos viridis. Anser decipio cras. Officia tempore vere. Crebro adimpleo vulariter depromo cupio. Desolo creta temporibus admoneo quo. Victus hic cursim consequatur adeptio cibo. Benigne aro perspiciatis amet. Dolorum abbas volubilis usque. Dens truculenter turpis coepi commodi similique corporis argumentum. Trans officiis tametsi eos corporis ultra. Cruciamentum virga correptius comprehendo congregatio. Adipiscor caterva cubitum corporis aeneus ultra quaerat terreo. Excepturi claudeo aliquid cernuus. Corrumpo sapiente averto trucido constans degenero averto illum patruus. Callide concido molestiae eligendi adeptio. Ultio triumphus vinitor ipsa expedita conservo defendo universe. Volo dolorum talus videlicet deserunt cogito.",
    amountContributed: 597,
    status: "active",
  },
  {
    id: 9,
    title: "ducimus somnus",
    target: 442,
    description:
      "Tibi alo vehemens patior eos utroque alioqui bardus arma ea. Caritas versus decerno tui usque voluptates deficio decimus comitatus. Acervus cuius benigne acsi vulgo. Vomer trucido denego vacuus alias thymum tantum sunt auctor attollo. Cresco comminor dolores caveo turba usitas veniam taceo cognomen. Cura super incidunt cibo absque convoco despecto dolore damnatio. Demens vereor vilicus abbas territo molestiae conventus. Sophismata pectus territo cras ademptio provident defleo tibi adfectus undique. Advenio cedo absens torqueo altus decretum ver clementia. Certe amita tres veritas commodo cunabula clibanus tremo. Decet culpa amet crinis testimonium solum. Tenax ait rerum accusamus. Sum arx creator terra constans arma. Pauper canis cras acsi adversus. Undique credo distinctio. Spargo verecundia cavus artificiose undique. Utroque curriculum contra cena vester adsum. Strues iste compello magnam cogo vomer autem defendo. Audax tondeo patria appono demo. Claudeo somnus defetiscor cattus qui. Doloribus coniuratio vereor curto. Tyrannus odit enim. Timidus summisse aegrus centum venustas cum tener summopere adinventitias apud. Stillicidium spargo rerum patria. Appositus corona adduco curriculum spargo caecus curo. Adicio tempora tum paens verecundia ultra crur maiores vinitor. Tribuo aer paulatim sint cognomen. Currus versus officiis. Consuasor provident carpo alioqui. Stella color tempore clementia valetudo trepide substantia curvo cura. Tutis conforto comburo. Exercitationem basium asperiores caput voluptatem admiratio comminor aeternus.",
    amountContributed: 80,
    status: "pending",
  },
  {
    id: 10,
    title: "dignissimos tres",
    target: 344,
    description:
      "Audeo strenuus valens defessus. Accusator laudantium custodia crastinus comptus pauper stella. Triduana vilicus amaritudo sustineo ars concido. Accendo vilicus corroboro dicta. In cogito aestivus ulciscor decens basium despecto libero. Tribuo tenax triduana apud. Totidem comis tibi. Sollicito somnus curtus natus deleniti sollers celo tristis vereor speculum. Pectus odio temporibus sufficio distinctio. Utique cupio paulatim ocer tonsor magnam. Vero tamen accusantium quasi sub. Dedecor ultio venia derideo peccatus eligendi vesper. Curatio depono provident vero talis cogo aqua. Verecundia cedo ascit thermae incidunt adsuesco voluptate temperantia vicinus sed. Absque arcus velut voluptatibus. Curatio doloremque terror exercitationem verus trepide calco aranea. Valeo combibo substantia curto tondeo vero testimonium tantillus. Calamitas vinculum corporis. Vicinus tutis adnuo arma spargo varius sub conor autus. Neque arcus conor ocer. Corporis corpus universe acer turbo decipio acidus ocer. Defendo aeger denuncio talis territo texo concedo celo appositus armarium. Agnitio vorax commodo aperiam enim cilicium. Cenaculum vicissitudo cibus adficio amicitia harum. Demens turba suffragium atrocitas adiuvo acies commodi amissio quo vergo. Sunt autem confero tendo conduco adsuesco. Auctus ancilla creta urbanus depereo aeternus tertius umerus. Bardus deinde crustulum. Cubitum curis accusator curis caterva. Degero vetus constans confido. Venia curis turpis caecus alter theologus sperno optio. Strues sublime crepusculum iure commodi sollicito alii ter. Carbo summisse recusandae arcus arceo absum usus consuasor thalassinus.",
    amountContributed: 190,
    status: "pending",
  },
  {
    id: 11,
    title: "dignissimos tres",
    target: 344,
    description:
      "Audeo strenuus valens defessus. Accusator laudantium custodia crastinus comptus pauper stella. Triduana vilicus amaritudo sustineo ars concido. Accendo vilicus corroboro dicta. In cogito aestivus ulciscor decens basium despecto libero. Tribuo tenax triduana apud. Totidem comis tibi. Sollicito somnus curtus natus deleniti sollers celo tristis vereor speculum. Pectus odio temporibus sufficio distinctio. Utique cupio paulatim ocer tonsor magnam. Vero tamen accusantium quasi sub. Dedecor ultio venia derideo peccatus eligendi vesper. Curatio depono provident vero talis cogo aqua. Verecundia cedo ascit thermae incidunt adsuesco voluptate temperantia vicinus sed. Absque arcus velut voluptatibus. Curatio doloremque terror exercitationem verus trepide calco aranea. Valeo combibo substantia curto tondeo vero testimonium tantillus. Calamitas vinculum corporis. Vicinus tutis adnuo arma spargo varius sub conor autus. Neque arcus conor ocer. Corporis corpus universe acer turbo decipio acidus ocer. Defendo aeger denuncio talis territo texo concedo celo appositus armarium. Agnitio vorax commodo aperiam enim cilicium. Cenaculum vicissitudo cibus adficio amicitia harum. Demens turba suffragium atrocitas adiuvo acies commodi amissio quo vergo. Sunt autem confero tendo conduco adsuesco. Auctus ancilla creta urbanus depereo aeternus tertius umerus. Bardus deinde crustulum. Cubitum curis accusator curis caterva. Degero vetus constans confido. Venia curis turpis caecus alter theologus sperno optio. Strues sublime crepusculum iure commodi sollicito alii ter. Carbo summisse recusandae arcus arceo absum usus consuasor thalassinus.",
    amountContributed: 190,
    status: "pending",
  },
  {
    id: 12,
    title: "dignissimos tres",
    target: 344,
    description:
      "Audeo strenuus valens defessus. Accusator laudantium custodia crastinus comptus pauper stella. Triduana vilicus amaritudo sustineo ars concido. Accendo vilicus corroboro dicta. In cogito aestivus ulciscor decens basium despecto libero. Tribuo tenax triduana apud. Totidem comis tibi. Sollicito somnus curtus natus deleniti sollers celo tristis vereor speculum. Pectus odio temporibus sufficio distinctio. Utique cupio paulatim ocer tonsor magnam. Vero tamen accusantium quasi sub. Dedecor ultio venia derideo peccatus eligendi vesper. Curatio depono provident vero talis cogo aqua. Verecundia cedo ascit thermae incidunt adsuesco voluptate temperantia vicinus sed. Absque arcus velut voluptatibus. Curatio doloremque terror exercitationem verus trepide calco aranea. Valeo combibo substantia curto tondeo vero testimonium tantillus. Calamitas vinculum corporis. Vicinus tutis adnuo arma spargo varius sub conor autus. Neque arcus conor ocer. Corporis corpus universe acer turbo decipio acidus ocer. Defendo aeger denuncio talis territo texo concedo celo appositus armarium. Agnitio vorax commodo aperiam enim cilicium. Cenaculum vicissitudo cibus adficio amicitia harum. Demens turba suffragium atrocitas adiuvo acies commodi amissio quo vergo. Sunt autem confero tendo conduco adsuesco. Auctus ancilla creta urbanus depereo aeternus tertius umerus. Bardus deinde crustulum. Cubitum curis accusator curis caterva. Degero vetus constans confido. Venia curis turpis caecus alter theologus sperno optio. Strues sublime crepusculum iure commodi sollicito alii ter. Carbo summisse recusandae arcus arceo absum usus consuasor thalassinus.",
    amountContributed: 190,
    status: "pending",
  },
  {
    id: 13,
    title: "dignissimos tres",
    target: 344,
    description:
      "Audeo strenuus valens defessus. Accusator laudantium custodia crastinus comptus pauper stella. Triduana vilicus amaritudo sustineo ars concido. Accendo vilicus corroboro dicta. In cogito aestivus ulciscor decens basium despecto libero. Tribuo tenax triduana apud. Totidem comis tibi. Sollicito somnus curtus natus deleniti sollers celo tristis vereor speculum. Pectus odio temporibus sufficio distinctio. Utique cupio paulatim ocer tonsor magnam. Vero tamen accusantium quasi sub. Dedecor ultio venia derideo peccatus eligendi vesper. Curatio depono provident vero talis cogo aqua. Verecundia cedo ascit thermae incidunt adsuesco voluptate temperantia vicinus sed. Absque arcus velut voluptatibus. Curatio doloremque terror exercitationem verus trepide calco aranea. Valeo combibo substantia curto tondeo vero testimonium tantillus. Calamitas vinculum corporis. Vicinus tutis adnuo arma spargo varius sub conor autus. Neque arcus conor ocer. Corporis corpus universe acer turbo decipio acidus ocer. Defendo aeger denuncio talis territo texo concedo celo appositus armarium. Agnitio vorax commodo aperiam enim cilicium. Cenaculum vicissitudo cibus adficio amicitia harum. Demens turba suffragium atrocitas adiuvo acies commodi amissio quo vergo. Sunt autem confero tendo conduco adsuesco. Auctus ancilla creta urbanus depereo aeternus tertius umerus. Bardus deinde crustulum. Cubitum curis accusator curis caterva. Degero vetus constans confido. Venia curis turpis caecus alter theologus sperno optio. Strues sublime crepusculum iure commodi sollicito alii ter. Carbo summisse recusandae arcus arceo absum usus consuasor thalassinus.",
    amountContributed: 190,
    status: "pending",
  },
  {
    id: 14,
    title: "dignissimos tres",
    target: 344,
    description:
      "Audeo strenuus valens defessus. Accusator laudantium custodia crastinus comptus pauper stella. Triduana vilicus amaritudo sustineo ars concido. Accendo vilicus corroboro dicta. In cogito aestivus ulciscor decens basium despecto libero. Tribuo tenax triduana apud. Totidem comis tibi. Sollicito somnus curtus natus deleniti sollers celo tristis vereor speculum. Pectus odio temporibus sufficio distinctio. Utique cupio paulatim ocer tonsor magnam. Vero tamen accusantium quasi sub. Dedecor ultio venia derideo peccatus eligendi vesper. Curatio depono provident vero talis cogo aqua. Verecundia cedo ascit thermae incidunt adsuesco voluptate temperantia vicinus sed. Absque arcus velut voluptatibus. Curatio doloremque terror exercitationem verus trepide calco aranea. Valeo combibo substantia curto tondeo vero testimonium tantillus. Calamitas vinculum corporis. Vicinus tutis adnuo arma spargo varius sub conor autus. Neque arcus conor ocer. Corporis corpus universe acer turbo decipio acidus ocer. Defendo aeger denuncio talis territo texo concedo celo appositus armarium. Agnitio vorax commodo aperiam enim cilicium. Cenaculum vicissitudo cibus adficio amicitia harum. Demens turba suffragium atrocitas adiuvo acies commodi amissio quo vergo. Sunt autem confero tendo conduco adsuesco. Auctus ancilla creta urbanus depereo aeternus tertius umerus. Bardus deinde crustulum. Cubitum curis accusator curis caterva. Degero vetus constans confido. Venia curis turpis caecus alter theologus sperno optio. Strues sublime crepusculum iure commodi sollicito alii ter. Carbo summisse recusandae arcus arceo absum usus consuasor thalassinus.",
    amountContributed: 190,
    status: "pending",
  },
  {
    id: 15,
    title: "dignissimos tres",
    target: 344,
    description:
      "Audeo strenuus valens defessus. Accusator laudantium custodia crastinus comptus pauper stella. Triduana vilicus amaritudo sustineo ars concido. Accendo vilicus corroboro dicta. In cogito aestivus ulciscor decens basium despecto libero. Tribuo tenax triduana apud. Totidem comis tibi. Sollicito somnus curtus natus deleniti sollers celo tristis vereor speculum. Pectus odio temporibus sufficio distinctio. Utique cupio paulatim ocer tonsor magnam. Vero tamen accusantium quasi sub. Dedecor ultio venia derideo peccatus eligendi vesper. Curatio depono provident vero talis cogo aqua. Verecundia cedo ascit thermae incidunt adsuesco voluptate temperantia vicinus sed. Absque arcus velut voluptatibus. Curatio doloremque terror exercitationem verus trepide calco aranea. Valeo combibo substantia curto tondeo vero testimonium tantillus. Calamitas vinculum corporis. Vicinus tutis adnuo arma spargo varius sub conor autus. Neque arcus conor ocer. Corporis corpus universe acer turbo decipio acidus ocer. Defendo aeger denuncio talis territo texo concedo celo appositus armarium. Agnitio vorax commodo aperiam enim cilicium. Cenaculum vicissitudo cibus adficio amicitia harum. Demens turba suffragium atrocitas adiuvo acies commodi amissio quo vergo. Sunt autem confero tendo conduco adsuesco. Auctus ancilla creta urbanus depereo aeternus tertius umerus. Bardus deinde crustulum. Cubitum curis accusator curis caterva. Degero vetus constans confido. Venia curis turpis caecus alter theologus sperno optio. Strues sublime crepusculum iure commodi sollicito alii ter. Carbo summisse recusandae arcus arceo absum usus consuasor thalassinus.",
    amountContributed: 190,
    status: "pending",
  },
  {
    id: 16,
    title: "dignissimos tres",
    target: 344,
    description:
      "Audeo strenuus valens defessus. Accusator laudantium custodia crastinus comptus pauper stella. Triduana vilicus amaritudo sustineo ars concido. Accendo vilicus corroboro dicta. In cogito aestivus ulciscor decens basium despecto libero. Tribuo tenax triduana apud. Totidem comis tibi. Sollicito somnus curtus natus deleniti sollers celo tristis vereor speculum. Pectus odio temporibus sufficio distinctio. Utique cupio paulatim ocer tonsor magnam. Vero tamen accusantium quasi sub. Dedecor ultio venia derideo peccatus eligendi vesper. Curatio depono provident vero talis cogo aqua. Verecundia cedo ascit thermae incidunt adsuesco voluptate temperantia vicinus sed. Absque arcus velut voluptatibus. Curatio doloremque terror exercitationem verus trepide calco aranea. Valeo combibo substantia curto tondeo vero testimonium tantillus. Calamitas vinculum corporis. Vicinus tutis adnuo arma spargo varius sub conor autus. Neque arcus conor ocer. Corporis corpus universe acer turbo decipio acidus ocer. Defendo aeger denuncio talis territo texo concedo celo appositus armarium. Agnitio vorax commodo aperiam enim cilicium. Cenaculum vicissitudo cibus adficio amicitia harum. Demens turba suffragium atrocitas adiuvo acies commodi amissio quo vergo. Sunt autem confero tendo conduco adsuesco. Auctus ancilla creta urbanus depereo aeternus tertius umerus. Bardus deinde crustulum. Cubitum curis accusator curis caterva. Degero vetus constans confido. Venia curis turpis caecus alter theologus sperno optio. Strues sublime crepusculum iure commodi sollicito alii ter. Carbo summisse recusandae arcus arceo absum usus consuasor thalassinus.",
    amountContributed: 190,
    status: "pending",
  },
  {
    id: 17,
    title: "vita ut",
    target: 344,
    description:
      "Audeo strenuus valens defessus. Accusator laudantium custodia crastinus comptus pauper stella. Triduana vilicus amaritudo sustineo ars concido. Accendo vilicus corroboro dicta. In cogito aestivus ulciscor decens basium despecto libero. Tribuo tenax triduana apud. Totidem comis tibi. Sollicito somnus curtus natus deleniti sollers celo tristis vereor speculum. Pectus odio temporibus sufficio distinctio. Utique cupio paulatim ocer tonsor magnam. Vero tamen accusantium quasi sub. Dedecor ultio venia derideo peccatus eligendi vesper. Curatio depono provident vero talis cogo aqua. Verecundia cedo ascit thermae incidunt adsuesco voluptate temperantia vicinus sed. Absque arcus velut voluptatibus. Curatio doloremque terror exercitationem verus trepide calco aranea. Valeo combibo substantia curto tondeo vero testimonium tantillus. Calamitas vinculum corporis. Vicinus tutis adnuo arma spargo varius sub conor autus. Neque arcus conor ocer. Corporis corpus universe acer turbo decipio acidus ocer. Defendo aeger denuncio talis territo texo concedo celo appositus armarium. Agnitio vorax commodo aperiam enim cilicium. Cenaculum vicissitudo cibus adficio amicitia harum. Demens turba suffragium atrocitas adiuvo acies commodi amissio quo vergo. Sunt autem confero tendo conduco adsuesco. Auctus ancilla creta urbanus depereo aeternus tertius umerus. Bardus deinde crustulum. Cubitum curis accusator curis caterva. Degero vetus constans confido. Venia curis turpis caecus alter theologus sperno optio. Strues sublime crepusculum iure commodi sollicito alii ter. Carbo summisse recusandae arcus arceo absum usus consuasor thalassinus.",
    amountContributed: 190,
    status: "pending",
  },
  {
    id: 18,
    title: "terror abscido",
    target: 344,
    description:
      "Audeo strenuus valens defessus. Accusator laudantium custodia crastinus comptus pauper stella. Triduana vilicus amaritudo sustineo ars concido. Accendo vilicus corroboro dicta. In cogito aestivus ulciscor decens basium despecto libero. Tribuo tenax triduana apud. Totidem comis tibi. Sollicito somnus curtus natus deleniti sollers celo tristis vereor speculum. Pectus odio temporibus sufficio distinctio. Utique cupio paulatim ocer tonsor magnam. Vero tamen accusantium quasi sub. Dedecor ultio venia derideo peccatus eligendi vesper. Curatio depono provident vero talis cogo aqua. Verecundia cedo ascit thermae incidunt adsuesco voluptate temperantia vicinus sed. Absque arcus velut voluptatibus. Curatio doloremque terror exercitationem verus trepide calco aranea. Valeo combibo substantia curto tondeo vero testimonium tantillus. Calamitas vinculum corporis. Vicinus tutis adnuo arma spargo varius sub conor autus. Neque arcus conor ocer. Corporis corpus universe acer turbo decipio acidus ocer. Defendo aeger denuncio talis territo texo concedo celo appositus armarium. Agnitio vorax commodo aperiam enim cilicium. Cenaculum vicissitudo cibus adficio amicitia harum. Demens turba suffragium atrocitas adiuvo acies commodi amissio quo vergo. Sunt autem confero tendo conduco adsuesco. Auctus ancilla creta urbanus depereo aeternus tertius umerus. Bardus deinde crustulum. Cubitum curis accusator curis caterva. Degero vetus constans confido. Venia curis turpis caecus alter theologus sperno optio. Strues sublime crepusculum iure commodi sollicito alii ter. Carbo summisse recusandae arcus arceo absum usus consuasor thalassinus.",
    amountContributed: 190,
    status: "pending",
  },
  {
    id: 19,
    title: "dignissimos tres",
    target: 344,
    description:
      "Audeo strenuus valens defessus. Accusator laudantium custodia crastinus comptus pauper stella. Triduana vilicus amaritudo sustineo ars concido. Accendo vilicus corroboro dicta. In cogito aestivus ulciscor decens basium despecto libero. Tribuo tenax triduana apud. Totidem comis tibi. Sollicito somnus curtus natus deleniti sollers celo tristis vereor speculum. Pectus odio temporibus sufficio distinctio. Utique cupio paulatim ocer tonsor magnam. Vero tamen accusantium quasi sub. Dedecor ultio venia derideo peccatus eligendi vesper. Curatio depono provident vero talis cogo aqua. Verecundia cedo ascit thermae incidunt adsuesco voluptate temperantia vicinus sed. Absque arcus velut voluptatibus. Curatio doloremque terror exercitationem verus trepide calco aranea. Valeo combibo substantia curto tondeo vero testimonium tantillus. Calamitas vinculum corporis. Vicinus tutis adnuo arma spargo varius sub conor autus. Neque arcus conor ocer. Corporis corpus universe acer turbo decipio acidus ocer. Defendo aeger denuncio talis territo texo concedo celo appositus armarium. Agnitio vorax commodo aperiam enim cilicium. Cenaculum vicissitudo cibus adficio amicitia harum. Demens turba suffragium atrocitas adiuvo acies commodi amissio quo vergo. Sunt autem confero tendo conduco adsuesco. Auctus ancilla creta urbanus depereo aeternus tertius umerus. Bardus deinde crustulum. Cubitum curis accusator curis caterva. Degero vetus constans confido. Venia curis turpis caecus alter theologus sperno optio. Strues sublime crepusculum iure commodi sollicito alii ter. Carbo summisse recusandae arcus arceo absum usus consuasor thalassinus.",
    amountContributed: 190,
    status: "pending",
  },
];
export default fakeCampaigns;
